
[gemini]
api_key = "AIzaSyDHyimi_DJP1IAQqRCIjNUIzkHjf_4lNC0"
model = "gemini/gemini-2.0-flash-exp"  # Optional, will default if omitted

[github]
api_key = "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"
model = "openai/gpt-4o-mini"  # Optional
api_base = "https://models.inference.ai.azure.com"  # Optional
